### ISSUE TITLE
Hourlies support

### ISSUE THREAD

**Issue by ericchu94** [Hamcha/lumaupdate#1]
Feel free to use http://arn.ericchu.net/ to get hourlies and pathchanging support.

For example:

| Path | Version | Binary url |
| --- | --- | --- |
| arm9loaderhax.bin | release | http://arn.ericchu.net/release/arm9loaderhax.bin |
| arm9loaderhax.bin | hourlies | http://arn.ericchu.net/latest/arm9loaderhax.bin |
| a9lh/payload.bin | release | http://arn.ericchu.net/release/a9lh/payload.bin |

**Comment by Hamcha** [comment]
Thanks for the offer!
I kinda wanted to do my own thing as a programming exercise and your service was the "if it doesn't work out I'll just use this guy's service".
I hope you won't feel bad but I'd like to avoid using your service unless I need to.

However if you ever implement a functionality that might be impractical to do on a 3DS I'll be happy to reconsider!

PS: Looking at the source code of your service, I see you do HTML scraping of the release page. Since you're using Node.js and therefore have JSON support builtin, you might want to consider using this [api](https://api.github.com/repos/AuroraWright/AuReiNand/releases/latest) instead, that'll cover you from possible layout changes (and/or avoid Github being angry at you if you get a pretty big traffic surge).

**Comment by ericchu94** [comment]
lol ok. Cutting down on dependencies has its benefits :)

Thanks for the api suggestion. I was in a rush to get something working, but I'll definitely look into it.

**Comment by ghost** [comment]
I would like hour-lies and Path changing support too! Hope it's somehow implemented in the future with this app!

**Comment by Hamcha** [comment]
Hourlies are in!
