### ISSUE TITLE
1.2.0 needs some minor cleanup

### ISSUE THREAD

**Issue by ksanislo** [Hamcha/lumaupdate#20]
source/release.cpp: Lines 15 and 16, you need to use a forward slash for include paths or you break compilation on Linux/Mac:
# include "minizip/ioapi_mem.h"
# include "minizip/unzip.h"
# 

source/arnutil.cpp: In function 'bool renameRecursive(const FS_Archive&, const string&, const string&)':
source/arnutil.cpp:87:21: warning: converting to non-pointer type 'Handle {aka long unsigned int}' from NULL [-Wconversion-null]
  Handle directory = NULL;

This should probably be 0, not NULL.
# 

source/release.cpp: In function 'bool extractZip(u8_, size_t, u8__, size_t_)':
source/release.cpp:282:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (res != *payloadSize) {

You can avoid the error with a cast of either (unsigned int)res or (int)*payloadSize, it's dealers choice, just be aware that you're mixing signed and unsigned in here, and things will get strange if you ever use this code with a > 2GB file.

**Comment by Hamcha** [comment]
Thanks for the reports, I’m about to go hunt for some memory issues so that’s gonna be helpful.

Can’t believe I didn’t notice the include path problem yet again.

Also as the payload size has a maximum size which is lower than megabytes I don’t think I’ll have many issues with the int/size_t checks
