### ISSUE TITLE
bootanim9 compatibility

### ISSUE THREAD

**Issue by brentblend** [Hamcha/lumaupdate#60]
If possible, it would be great to add bootanim9 support. 

Luma updater currently fails if you are using bootanim9 payload, "arm9loaderhax_si.bin" with the users old arm9loaderhax.bin now named arm9payload.bin and located in the bootanim folder then it becomes obvious why the updater would fail.

It isn't at all necessary, but it would be nice to be able to use this alongside bootanim9.

**Comment by Nils0990** [comment]
Same Problem here, got this in my config:

payload type = a9lh
payload path = /anim/arm9payload.bin
log enable = yes
selfupdate = yes
backup = yes

It updates without error. But it doesnt update the payload to luma 6.6 ;(

**Comment by brentblend** [comment]
@Nils0990 
It will probably be tough because of the arm9payload.bin renamed from arm9loaderhax.bin
and the arm9loaderhax.bin being renamed to arm9loaderhax_si.bin for newer a9lh users.

There would have to be a version check, I'd assume, for the a9lh payload itself. Then a series of renaming and relocating. 

In a perfect world, bootanim9 would just patch itself against the payload in use. So there wasn't any renaming or relocating.

That, or a bootanim9 cia that would run a version check, and then allow you to run the install process via a GUI instead of manually.

Hoping it wouldn't be too much work to have one, or the other.

**Comment by Nils0990** [comment]
Thank you for the answer. Maybe i delete bootanim9 or copy the payloads manually.

**Comment by GabyPCgeeK** [comment]
I too was having trouble updating luma with "payload path = /anim/arm9payload.bin". The arm9payload.bin.bak was created ok but arm9payload.bin would stay the same.
I downloaded the lumaupdate code and found in update.cpp the line that "opens/creates" the output file

_**std::ofstream a9lhfile("/" + args.payloadPath, std::ofstream::binary);**_

and the line that "opens/creates" the back up

_**std::ofstream target(backupName, std::ofstream::binary);**_

in the first one I noticed that it was adding an aditional / to the path that already began with / thanks to a check done in main.cpp.
I changed the line to:

_**std::ofstream a9lhfile(args.payloadPath, std::ofstream::binary);**_

and now lumaupdate updates /anim/arm9payload.bin successfully.

I also added a way in config to bypass the payload patches because bootanim9 does that
and also added the writing of the payload to /luma/arm9loaderhax.bin so I only need to copy/paste the file to CTRNAND.
