### ISSUE TITLE
No internet causes reboot

### ISSUE THREAD

**Issue by Pitel** [Hamcha/lumaupdate#67]
Starting the updater without internet causes crash and reboot. I think it should be handled more gracefuly.

**Comment by kopfpilot** [comment]
Starting the updater when the request limit to api.github.com is exceeded does the same. A graceful implementation could point out that a) the url is not acessible because of a missing internet connection and b) the url is not accessible because the request limit is exceeded for that internet connection (=wan ip).

**Comment by rctgamer3** [comment]
This also happens whenever it has a network connection but the connection to the set proxy server doesn't succeed.
